name: default

on:
  pull_request:
  push:
    branches:
      - master
      - renovate/reconfigure

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: '20'


jobs:
  spellcheck:
    uses: finleyfamily/workflows/.github/workflows/spellcheck.yml@master
    with:
      node-version: '20'
