name: On Push

on: push

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: '20'


jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: make spellcheck
