name: pull_request_target (opened)

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  workflows:
    uses: finleyfamily/workflows/.github/workflows/pr.assign-author.yml@master
